apiVersion: v1
kind: Service
metadata:
  name: shopify-clone-backend
spec:
  selector:
    app: shopify-clone
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
